# Generated by Django 4.2 on 2023-04-24 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroCliente', '0006_cliente_profissao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profissao',
            options={'verbose_name': 'Profissão', 'verbose_name_plural': 'Profissões'},
        ),
    ]
