# Generated by Django 4.2 on 2023-04-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroCliente', '0012_cliente_interesses'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefone',
            name='nome',
            field=models.CharField(choices=[('cel', 'Celular'), ('Res', 'Residencial'), ('Con', 'Comercial')], max_length=15, null=True),
        ),
    ]
