# Generated by Django 4.2 on 2023-05-03 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CadastroCliente', '0013_telefone_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='Profissao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CadastroCliente.profissao', verbose_name='Prosissão'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ativo',
            field=models.BooleanField(verbose_name='Ativo?'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(max_length=250, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero',
            field=models.CharField(max_length=5, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='ddd',
            field=models.CharField(max_length=2, null=True, verbose_name='DDD'),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='numero',
            field=models.CharField(max_length=10, null=True, verbose_name='Número'),
        ),
    ]
